baseURL = "https://karaokay.projectbread.uk"
languageCode = "en-gb"
title = "Karaokay"
theme = "ananke"
[params]
  Subtitle = "Open source karaoke songbook, song recommendations and playlist tracker app"
